name: JW website CI/CD

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '17 4 * * *'
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [15.x]
    
    name: Fetch data, build React app, and upload to S3 bucket

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install requests

      - name: Python fetch of json file from Vinmonopolet    
        run: python scripts/python_jsonfetch.py --api-key ${{ secrets.VINMONOPOLET_OPEN_API_KEY }}


      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.5.0' # The R version to download (if necessary) and use.
      
      - name: Install tidyverse linux dependencies
        run : sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages and transform json data to csv file using R
        run: sudo Rscript scripts/transform_data.R

      - name: Install Node dependencies
        run: npm ci
      - name: Build React application
        run: npm run build

      - name: Upload build to AWS
        uses: SigSel/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
          
      - name: Upload json artifact
        uses: actions/upload-artifact@v3
        with:
          path: scripts/search.json
          
      - name: Upload csv artifact
        uses: actions/upload-artifact@v3
        with:
          path: src/JW_vinmon.csv
            
